apiVersion: v1
kind: Secret
metadata:
  name: forge-agent-enrollment
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  enrollment-token: {{ .Values.enrollment.token | quote }}
