apiVersion: v1
kind: Secret
metadata:
  name: forge-byoc-secrets
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  pg-dsn:           {{ .Values.dependencies.postgres.dsn | quote }}
  redis-addr:       {{ .Values.dependencies.redis.addr | quote }}
  redis-password:   {{ .Values.dependencies.redis.password | quote }}
  clickhouse-addr:  {{ .Values.dependencies.clickhouse.addr | quote }}
  clickhouse-user:  {{ .Values.dependencies.clickhouse.username | quote }}
  clickhouse-pass:  {{ .Values.dependencies.clickhouse.password | quote }}
  relay-api-key:    {{ .Values.forge.relayAPIKey | quote }}
